"""add parent to section

Revision ID: b1049aaf00bc
Revises: 89ac2fcd84db
Create Date: 2026-03-03 01:48:04.307631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1049aaf00bc"
down_revision: Union[str, Sequence[str], None] = "89ac2fcd84db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sections", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "sections", "sections", ["parent_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sections", type_="foreignkey")
    op.drop_column("sections", "parent_id")
    # ### end Alembic commands ###
